#!/usr/bin/env python

from bakery.bakefile import *
from bakery.buildchain import *
from bakery.core import *

load_extensions()
b = Bakefile()
b.load("./Bakefile")

for i in b.items:
    print 'in', i.inputs
    print 'out', i.outputs
    print 'pattern', i.pattern
    print 'deps', i.deps

    print 'imp', i.chain._import_step.name, i.chain._import_step.args
    for s in i.chain._process_steps:
        print 'proc', s.name, s.args
    print 'exp', i.chain._export_step.name, i.chain._export_step.args

